apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: service-a-alerts
  namespace: monitoring
  labels:
    release: monitoring
spec:
  groups:
    - name: service-a.rules
      rules:
        - alert: HighCPUUsage
          expr: sum(rate(container_cpu_usage_seconds_total{pod=~"service-a-.*"}[2m])) > 0.5
          for: 2m
          labels:
            severity: warning
          annotations:
            summary: "High CPU usage detected"
            description: "Service-a pods are using high CPU"
        - alert: PodRestarting
          expr: increase(kube_pod_container_status_restarts_total{pod=~"service-a-.*"}[5m]) > 0
          for: 1m
          labels:
            severity: critical
          annotations:
            summary: "Pod restarting frequently"
            description: "Service-a pod restarted recently"